Document how to run it
WS22-23-SWEPM3ILV-INF-BA-VZ-Group-2/API pull request #17
Opened 2022-11-16 17:42 UTC by MelvinPariyadan

Closes #2

2022-11-16 21:12 UTC, LBeghini requested changes
Pretty obvious you just copy paste from the documentation, which is ok, but you also copy the commands to create the project again. What should be mentioned it is only the commands necessary to run the application.

2022-11-16 21:12 UTC, LBeghini commented on README.md
> +POST /api/auth/signout logout the account
```suggestion

```

2022-11-16 21:12 UTC, LBeghini commented on README.md
> +MongoDB
```suggestion
- Express 4.17.1
- cookie-session 1.4.0
- bcryptjs 2.4.3
- jsonwebtoken 8.5.1
- mongoose 5.13.13
- MongoDB
```

2022-11-16 21:12 UTC, LBeghini commented on README.md
> +mkdir node-js-express-login--mongodb
````suggestion

````

2022-11-16 21:12 UTC, LBeghini commented on README.md
> +cd node-js-express-login--mongodb
````suggestion

````

2022-11-16 21:12 UTC, LBeghini commented on README.md
> +npm init
```suggestion

```

2022-11-16 21:12 UTC, LBeghini commented on README.md
> +npm install express mongoose cors cookie-session jsonwebtoken bcryptjs --save
````suggestion
```shell
npm install  --save
````

2022-11-16 21:12 UTC, LBeghini commented on README.md
> +});
```suggestion

```

2022-11-16 21:12 UTC, LBeghini commented on README.md
> +node server.js
````suggestion
```shell
node server.js
```
````

2022-11-16 22:15 UTC, SaraGrimaldi approved these changes

2022-11-17 10:44 UTC, LBeghini requested changes

2022-11-17 10:44 UTC, LBeghini commented on README.md
> +
````suggestion
```
````

2022-11-17 10:47 UTC, LBeghini approved these changes

2022-11-17 10:51 UTC, merged