13-add-place-function
WS22-23-SWEPM3ILV-INF-BA-VZ-Group-2/API pull request #65
Opened 2022-12-14 18:46 UTC by dominikJakov

closes #13

2022-12-14 18:49 UTC, Kaloyan-Stoyanov approved these changes

2022-12-14 21:08 UTC, Keytush approved these changes

2022-12-15 06:15 UTC, MelvinPariyadan requested changes
![image](https://user-images.githubusercontent.com/100207064/207785326-75b2fcc5-64f7-4461-b91b-155b26ecde1b.png)

Hey just in the pylint file make these changes. Basically some lines are too long and imports should be  third party imports first and then our own imports. Its a quick fix. In .pylintrc file inside the disable = [...] you have to add C01C03. We basically want to disable all django specific pylint issues. But not the rest. I think there are also conflicts. Just on vscode go to source control. Here if there are conflicts just fix em. And then it should all work

2022-12-15 09:41 UTC, MelvinPariyadan approved these changes

2022-12-15 09:41 UTC, merged