12-find-places
WS22-23-SWEPM3ILV-INF-BA-VZ-Group-2/API pull request #79
Opened 2022-12-17 21:43 UTC by dominikJakov

Closes #12

2022-12-17 21:57 UTC, MelvinPariyadan submitted a review, later dismissed

2022-12-17 22:37 UTC, LBeghini requested changes

2022-12-17 22:37 UTC, LBeghini commented on tests/test_views.py
> +        self.assertEqual(response.status_code, status.HTTP_200_OK)
The test should assert that were retrieved exactly three places from the response

2022-12-17 22:39 UTC, LBeghini requested changes

2022-12-17 22:39 UTC, LBeghini commented on unreveal/views.py
> +            range = self.request.query_params.get('range')
`range` is a built in function in python, this variable should be renamed

2022-12-18 11:38 UTC, Keytush submitted a review, later dismissed

2022-12-20 10:56 UTC, MelvinPariyadan approved these changes, later dismissed

2022-12-20 18:56 UTC, LBeghini approved these changes

2022-12-20 18:56 UTC, LBeghini commented on tests/test_views.py
> +        self.assertEqual(len(response.content.decode("utf-8").strip('[]').split('},{')),2)
What does it do?

2022-12-20 18:56 UTC, LBeghini commented on tests/test_views.py
> +        self.assertEqual(len(response.content.decode("utf-8").strip('[]').split('},{')),2)
@dominikJakov ?

2022-12-20 19:09 UTC, MelvinPariyadan approved these changes

2022-12-20 19:13 UTC, Keytush approved these changes

2022-12-20 19:26 UTC, merged